Bryan
4site-interactive-studios/engrid-aiusa pull request #10
Opened 2021-03-16 04:39 UTC by bryancasler

2021-03-16 10:19 UTC, tjstalcup approved these changes

2021-03-17 15:53 UTC, fernanDOTdo requested changes

2021-03-17 15:53 UTC, fernanDOTdo commented on src/index.ts
> +import { Options, App } from "../../engrid-scripts/packages/common"; // Uses ENGrid via Visual Studio Workspace
We should undo this.

2021-03-17 15:53 UTC, fernanDOTdo commented on src/sass/main.scss
> +@import "../../../engrid-scripts/packages/styles"; // Uses ENGrid via Visual Studio Workspace
We should undo this.

2021-03-17 15:53 UTC, fernanDOTdo commented on src/templates/page-donation-aiusa.html
> +    <script>
Is this part a Test/WIP?

2021-03-17 15:53 UTC, fernanDOTdo commented on src/templates/page-donation-aiusa.html
> +          <div class="en__component en__component--contactblock" style="">
Should we create a separated file for this? It does not look like this is related to donations.

2021-03-21 17:43 UTC, merged